// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtlCGgc4vZ8HCn4PXGRfJEIIF6O_IFyQ0',
    appId: '1:37876147762:web:e61c094944cf1d8f11fe2b',
    messagingSenderId: '37876147762',
    projectId: 'ttestt-b6048',
    authDomain: 'ttestt-b6048.firebaseapp.com',
    databaseURL: 'https://ttestt-b6048-default-rtdb.firebaseio.com',
    storageBucket: 'ttestt-b6048.firebasestorage.app',
    measurementId: 'G-8MZ12TLVYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp7D5be9rh6TIF99Z9Z0HSvdjjliaIHZg',
    appId: '1:37876147762:android:4d5cacb88d55d79b11fe2b',
    messagingSenderId: '37876147762',
    projectId: 'ttestt-b6048',
    databaseURL: 'https://ttestt-b6048-default-rtdb.firebaseio.com',
    storageBucket: 'ttestt-b6048.firebasestorage.app',
  );
}
